### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by dustalov** [nlpub/watset-java#10]
Watset is mature enough to be deployed to the Maven Central.

**Comment by dustalov** [comment]
Application: https://issues.sonatype.org/browse/OSSRH-59137

**Comment by dustalov** [comment]
* https://docs.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository
* https://central.sonatype.org/pages/ossrh-guide.html

**Comment by dustalov** [comment]
Watset is in Maven Central now!

* https://repo.maven.apache.org/maven2/org/nlpub/watset/

**Comment by stefan-ka** [comment]
Hi @dustalov, 
Would it be possible to publish v2.1.3 into Maven central? I would love to try out your algorithms in a project, but unfortunately I'm stuck with Java 8 there :( 
Or have you published your library into another Maven repository where I can find a version compatible with Java 8?
Thanks and best regards,
Stefan

**Comment by dustalov** [comment]
Hi @stefan-ka, sure, I can release the latest version of Watset which is compatible with Java 8. It will require a few changes, but nothing critical. As a workaround, you can obtain v2.1.3 from JitPack or GitHub Packages right now:

* <https://jitpack.io/#nlpub/watset-java/2.1.3>
* <https://github.com/nlpub/watset-java/packages/16148?version=2.1.3>

**Comment by dustalov** [comment]
I have just published v2.1.5 to Maven Central. It should be available within a few hours. Additionally, it is available on JitPack and GitHub Packages.

**Comment by stefan-ka** [comment]
Thanks @dustalov 👍🙏
Works perfectly fine...
