### ISSUE TITLE
Deploy jar to maven repository

### ISSUE THREAD

**Issue by Pavlmits** [nlpub/watset-java#3]
I think that you have made great job!! I would really like to reuse your algorithms and I think I am not the only one. So for a smooth reuse for all of the users can you deploy the jar on maven repository?

**Comment by dustalov** [comment]
Thank you for the kind words! I have been thinking about this a lot, but a proper deployment to something like Maven Central seems to take slightly more time than I currently have.

However, a simple workaround through a third-party service called JitPack that performs packaging is available: <https://jitpack.io/#nlpub/watset-java>. To use it, you can add one more repository to your `pom.xml`:

```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

Then you can add `watset-java` as a regular dependency:

```xml
<dependency>
    <groupId>com.github.nlpub</groupId>
    <artifactId>watset-java</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>
```

In the near future, I plan to try rolling out releases to GitHub Packages.

**Comment by Pavlmits** [comment]
Thank you very much for alternative! Great job!

**Comment by dustalov** [comment]
A small update. Watset is now available via the GitHub Package Registry: <https://github.com/nlpub/watset-java/packages/16148>.
